**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

In [1]:
import numpy as np

###`Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [3]:
#Code here
a=np.nan*np.empty(10)
a[4]=10
print(a)

[nan nan nan nan 10. nan nan nan nan nan]


###`Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [6]:
#Code here
a,b=map(int,input().split())
x=np.random.random((a,b))
print(x)
print(x.mean())

2 3
[[0.18052545 0.01029442 0.5768149 ]
 [0.41425816 0.91408309 0.11134133]]
0.3678862258783106


###`Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [17]:
# My Code here
a,b=map(int,input().split())
def arrayBorder(a,b):
    t=np.ones((a,b))
    t[1:-1,1:-1]=0
    return t
arrayBorder(a,b)

2 4


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

###`Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [14]:
# my Code 
a=np.random.random(10)
a

array([0.73132567, 0.24070464, 0.2786812 , 0.06988732, 0.85747617,
       0.73743201, 0.25306362, 0.37589781, 0.22789108, 0.90048402])

In [19]:
#Code here
a=np.linspace(0,1,12)[1:-1]
a

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

###`Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [21]:
#Code here
# Never we cannot create identity matrix bcoz init rows and columns should be of same number
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

###`Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [22]:
#Code here
z=np.zeros((5,5))
z+=np.arange(5)
print(z)


[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


###`Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3]) 
```


In [38]:
#code here
a=np.random.randint(1,100,(10,2))
print(a)
p=np.array([2,3])
np.sqrt(np.sum((a-p)**2,axis=1)).astype(int)


[[11 42]
 [79 89]
 [22 39]
 [54 51]
 [37 23]
 [ 2 71]
 [26 19]
 [64 44]
 [74 76]
 [88  1]]


array([ 40, 115,  41,  70,  40,  68,  28,  74, 102,  86])

###`Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [30]:
#Code here
np.arange(336).reshape(6,7,8)
np.unravel_index(100,(6,7,8))


(1, 5, 4)

### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [36]:
#Code here
a=input().strip().split()
np.array(a[::-1]).astype(float)

1 2 3 4


array([4., 3., 2., 1.])

### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [37]:
#Code here
np.size(a)

4

### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01, 
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [40]:
#Code here
import numpy as np
def softmax(arr):
    if type(arr) !=np.ndarray:
        raise TypeError('Requires Numpy Array')
    elif arr.ndim >1:
        raise TypeError('Required 1D array')
    else:
        s=np.sum(np.exp(arr))
        return np.exp(arr)/s

softmax(np.arange(5))

array([0.01165623, 0.03168492, 0.08612854, 0.23412166, 0.63640865])

### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]] 
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [42]:
#Coder here
def vertical_stack(*args):
    for i in args:
        if type(i) != np.ndarray:
            raise TypeError("Requires Numpy Array")
        else:
            return np.vstack(args)

a=np.arange(10).reshape(2,-1)
print('a=',a)
b=np.arange(10).reshape(2,-1)
print('b=',b)
vertical_stack(a,b)

a= [[0 1 2 3 4]
 [5 6 7 8 9]]
b= [[0 1 2 3 4]
 [5 6 7 8 9]]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [ ]:
#Code here
de date_array(start:str,end:str):
    if type(start) !=str or type(end) !=str:
        raise TypeError
    np.range(start,end,dtype="")

###`Q-14:` Subtract the mean of each row from a matrix.

In [51]:
#code here
#arr=np.random.random((5,4))
arr=np.arange(20).reshape((5,4))
print(arr)
print(arr.mean(axis=1))
#keepdims convet it into(5,1)
print(arr.mean(axis=1,keepdims=True))
arr-arr.mean(axis=1,keepdims=True)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[ 1.5  5.5  9.5 13.5 17.5]
[[ 1.5]
 [ 5.5]
 [ 9.5]
 [13.5]
 [17.5]]


array([[-1.5, -0.5,  0.5,  1.5],
       [-1.5, -0.5,  0.5,  1.5],
       [-1.5, -0.5,  0.5,  1.5],
       [-1.5, -0.5,  0.5,  1.5],
       [-1.5, -0.5,  0.5,  1.5]])

###`Q-15:` Swap column-1 of array with column-2 in the array.

In [59]:
#Code here
arr=np.random.randint(1,10,(5,4))
print(arr)
arr[:,[0,2,1,3]]

[[6 2 1 5]
 [9 7 3 4]
 [4 2 6 4]
 [3 3 3 9]
 [3 8 5 7]]


array([[6, 1, 2, 5],
       [9, 3, 7, 4],
       [4, 6, 2, 4],
       [3, 3, 3, 9],
       [3, 5, 8, 7]])

###`Q-16:` Replace odd elements in arrays with -1.

In [65]:
#Code here
arr=np.arange(9).reshape(3,3)
arr[arr%2==1]=-1
arr
        



array([[ 0, -1,  2],
       [-1,  4, -1],
       [ 6, -1,  8]])

###`Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
``` 

In [69]:
#Code here
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])
arr=np.array([a,b])
arr
print(np.max(arr,axis=0))


[6 3 1 7 8]


###`Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [70]:
# Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

array([[7127, 3039, 5978, 2487, 8602],
       [8456, 9319, 7797, 5492, 9913],
       [9464, 8051, 7774, 8894, 2204],
       [2762, 8314,  249,  501, 7820],
       [6756, 8050, 8456, 7942, 4176],
       [4050,  239, 2928, 3073, 5594],
       [3022, 4411, 2091, 6262, 2919],
       [6582, 4848, 6620, 8036, 7033]])

In [77]:
#Code here
#Fetch Every alternate column of the array
arr1[:,::2]

array([[7127, 5978, 8602],
       [8456, 7797, 9913],
       [9464, 7774, 2204],
       [2762,  249, 7820],
       [6756, 8456, 4176],
       [4050, 2928, 5594],
       [3022, 2091, 2919],
       [6582, 6620, 7033]])

In [80]:
arr1

array([[7127, 3039, 5978, 2487, 8602],
       [8456, 9319, 7797, 5492, 9913],
       [9464, 8051, 7774, 8894, 2204],
       [2762, 8314,  249,  501, 7820],
       [6756, 8050, 8456, 7942, 4176],
       [4050,  239, 2928, 3073, 5594],
       [3022, 4411, 2091, 6262, 2919],
       [6582, 4848, 6620, 8036, 7033]])

In [81]:
(arr1-arr1.min())/(arr1.max()-arr1.min())

array([[0.71201158, 0.2894356 , 0.59323961, 0.23237544, 0.86448212],
       [0.84939012, 0.9385983 , 0.78126938, 0.54300186, 1.        ],
       [0.95358693, 0.80752533, 0.77889188, 0.89466612, 0.20312177],
       [0.26080215, 0.8347116 , 0.0010337 , 0.0270829 , 0.78364689],
       [0.67366136, 0.80742196, 0.84939012, 0.79625801, 0.40696713],
       [0.39394253, 0.        , 0.27796155, 0.29295018, 0.55354559],
       [0.28767831, 0.43125904, 0.19144098, 0.62259665, 0.27703122],
       [0.65567501, 0.47643167, 0.65960306, 0.80597478, 0.70229481]])

###`Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [85]:
#Code here
def lar_arr(arr,n):
    arr=np.sort(arr)
    return arr[-n]
arr=np.arange(10)
n=3
lar_arr(arr,n)

7

###`Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [86]:
#code here
a = np.array([1,2,3])
np.hstack((np.repeat(a,3),np.tile(a,3)))

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])