###`Q-1:` Create a random 3x4 matrix with value between 0-100. And perform below tasks

    i. Sort this matrix. np.sort()
    ii. Sort this matrix based on values in 2nd column.
    iii. Sort this matrix based on max value in each row.
    iv. Sort based on elements value.


See examples:
```
arr = 
    [[92 90 74]
    [ 6 63 93]
    [15 93 96]
    [70 60 48]]
```
```
i. np.sort
[[74 90 92]
 [ 6 63 93]
 [15 93 96]
 [48 60 70]]

ii. based on 2nd column
[[70 60 48]
 [ 6 63 93]
 [92 90 74]
 [15 93 96]]

iii. based on row max- ascending
[[15 93 96]
 [ 6 63 93]
 [92 90 74]
 [70 60 48]]

iv. based on elements value
[[ 6 15 48]
 [60 63 70]
 [74 90 92]
 [93 93 96]]

```

In [11]:
# My code here
import numpy as np
arr =np.array([[92,90,74],[6,63,93],[15,93,96],[70,60,48]])
print(arr)
#i
print('i==\n',np.sort(arr,axis=1))
print()
#print('ii--\n',np.sort(arr[:,1],axis=0))
print(np.sort(arr))
#sort array based on elements
print(np.sort(arr,axis=None).reshape(-1,3))

[[92 90 74]
 [ 6 63 93]
 [15 93 96]
 [70 60 48]]
i==
 [[74 90 92]
 [ 6 63 93]
 [15 93 96]
 [48 60 70]]

[[74 90 92]
 [ 6 63 93]
 [15 93 96]
 [48 60 70]]
[[ 6 15 48]
 [60 63 70]
 [74 90 92]
 [93 93 96]]


In [10]:
import numpy as np
arr=np.random.randint(0,100,(4,3))
print(arr)
print(np.sort(arr))
#sort based on 2nd Column
print(arr[arr[:,1].argsort()])
#sort based on max row number
print(np.array(sorted(arr,key=lambda x:max(x))))
#

[[72 49 83]
 [ 2  9 64]
 [78 55  9]
 [12 86 15]]
[[49 72 83]
 [ 2  9 64]
 [ 9 55 78]
 [12 15 86]]
[[ 2  9 64]
 [72 49 83]
 [78 55  9]
 [12 86 15]]


array([[ 2,  9, 64],
       [78, 55,  9],
       [72, 49, 83],
       [12, 86, 15]])

###`Q-2:` There is an array of marks of 5 students in 4 subjects. Further you are asked to perform below task.
    i. Add marks every student of an extra subject in the same array.
    ii. Add two new students marks in respective 5 subjects.(one subject added in above task)
    iii. Add extra column with sum of all subjects(5-subjects) marks
    iv. Sort the array(non-ascending order) on total marks column--one added in above task. Show top 2 rows.

Note: Change dimension of arrays during concatenation or appending if required.

Given Array-
```
marks = [[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]]

extra_subject = [41, 87, 72, 36, 92]
#Two extra students record-
rec1 = [77, 83, 98, 95, 89]
rec2 = [92, 71, 52, 61, 53]
```

In [12]:
# My code here
marks = [[13,10,9,33],
       [63,46,90,42],
       [39,76,13,29],
       [82,9,29,78],
       [67,61,59,36]]
extra_subject=[41,87,72,36,92]
print(np.expand_dims(extra_subject,axis=1))
np.append(marks,np.expand_dims(extra_subject,axis=1))

[[41]
 [87]
 [72]
 [36]
 [92]]


array([13, 10,  9, 33, 63, 46, 90, 42, 39, 76, 13, 29, 82,  9, 29, 78, 67,
       61, 59, 36, 41, 87, 72, 36, 92])

In [27]:
#Sir k Code
marks =np.array([[13,10,9,33],
       [63,46,90,42],
       [39,76,13,29],
       [82,9,29,78],
       [67,61,59,36]])
extra_subject=np.array([41,87,72,36,92]).reshape(-1,1)
print(extra_subject)
#add extra_subject to marks
marks=np.concatenate((marks,extra_subject),axis=1)
print(marks)

#add Two extra students record-
rec1 = np.array([77, 83, 98, 95, 89]).reshape(1,-1)
rec2 = np.array([92, 71, 52, 61, 53]).reshape(1,-1)
marks=np.concatenate((marks,rec1,rec2),axis=0)
print(marks)


#add column with will give the sum of all the subject
sum_sub=marks.sum(axis=1).reshape(-1,1)
marks=np.concatenate((marks,sum_sub),axis=1)
print(marks)

#iv. Sort the array(non-ascending order) on total marks column--one added in above task. Show top 2 rows.
print(np.array(sorted(marks,key=lambda x:x[-1],reverse=True))[:2,:])


[[41]
 [87]
 [72]
 [36]
 [92]]
[[13 10  9 33 41]
 [63 46 90 42 87]
 [39 76 13 29 72]
 [82  9 29 78 36]
 [67 61 59 36 92]]
[[13 10  9 33 41]
 [63 46 90 42 87]
 [39 76 13 29 72]
 [82  9 29 78 36]
 [67 61 59 36 92]
 [77 83 98 95 89]
 [92 71 52 61 53]]
[[ 13  10   9  33  41 106]
 [ 63  46  90  42  87 328]
 [ 39  76  13  29  72 229]
 [ 82   9  29  78  36 234]
 [ 67  61  59  36  92 315]
 [ 77  83  98  95  89 442]
 [ 92  71  52  61  53 329]]
[[ 77  83  98  95  89 442]
 [ 92  71  52  61  53 329]]


###`Q-3:` Find unique arrays from a 2D array column wise and row wise.
```
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])
```
Expected Result-
```
Row Wise
[[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]

Col Wise
[[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]
```

In [28]:
# code here
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])
print(np.unique(arr,axis=0))#rows unique
print(np.unique(arr,axis=1))#columns wise


[[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]
[[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]


###`Q-4:` Flip given 2-D array along both axes at the same time.

In [30]:
# code here
print(arr)
print(np.flip(arr,axis=[0,1]))

[[1 2 3 3 1 1]
 [0 9 1 2 8 8]
 [1 2 3 8 8 8]
 [1 2 3 3 1 1]]
[[1 1 3 3 2 1]
 [8 8 8 3 2 1]
 [8 8 2 1 9 0]
 [1 1 3 3 2 1]]


### `Q-5:` Get row numbers of NumPy array having element larger than X.
```
arr = [[1,2,3,4,5], 
      [10,-3,30,4,5], 
      [3,2,5,-4,5], 
      [9,7,3,6,5]] 

X = 6
```

In [34]:
#Sir ka shi Code using np.any
arr =np.array([[1,2,3,4,5], 
      [10,-3,30,4,5], 
      [3,2,5,-4,5], 
      [9,7,3,6,5]])
np.where(np.any(arr>6,axis=1))

(array([1, 3], dtype=int64),)

In [36]:
# code here
arr =np.array([[1,2,3,4,5], 
      [10,-3,30,4,5], 
      [3,2,5,-4,5], 
      [9,7,3,6,5]])
np.unique(np.where(arr>6)[0])

array([1, 3], dtype=int64)

### `Q-6:` How to convert an array of arrays into a flat 1d array?


In [39]:
# These arrays are given.
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

In [40]:
# code here
np.concatenate([arr1,arr2,arr3])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### `Q-7:` You are given a array. You have to find the minimum and maximum array element and remove that from the array.

```python
import numpy as np

np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
```

In [78]:
# code here
import numpy as np

np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))

In [87]:
arr

array([[448, 563, 418, 240, 507, 362, 345, 236, 719, 291, 298, 639, 458,
        387, 262, 613, 267, 882, 181, 425, 790, 635, 889, 818, 872, 967,
        277, 470, 336, 920, 917, 295, 557, 830, 506, 385, 353, 975, 592,
        997, 137, 340, 222, 215, 472, 459, 617, 649, 935, 956, 914, 932,
        645, 952, 921, 490, 527, 972, 278, 307, 840, 958, 246, 449, 251,
        957, 103, 627, 920, 824, 356, 825, 173, 323, 372, 960, 710, 464,
        244, 782, 763, 635, 436, 774, 171, 469, 178, 458, 624, 211, 771,
        270, 308, 231, 952, 514, 699, 702, 433, 900, 373, 318, 998, 265,
        503, 320, 230, 324, 922, 967, 620, 743, 527, 117, 566, 804, 123,
        946, 587, 227, 853, 757, 944, 328, 855, 930, 325, 729, 426, 514,
        296, 879, 575, 936, 705, 209, 191, 743, 510, 513, 628, 559, 658,
        528, 395, 525, 922, 136, 496, 225, 895, 975, 263, 908, 420, 711,
        800, 976, 786, 235, 930, 859, 618, 226, 695, 460, 218, 483, 490,
        803, 621, 453, 193, 607, 677, 637, 728, 724

In [88]:
arr[0,np.argmax(arr)]

998

In [91]:
np.delete(arr,np.argmax(arr))

array([448, 563, 418, 240, 507, 362, 345, 236, 719, 291, 298, 639, 458,
       387, 262, 613, 267, 882, 181, 425, 790, 635, 889, 818, 872, 967,
       277, 470, 336, 920, 917, 295, 557, 830, 506, 385, 353, 975, 592,
       997, 137, 340, 222, 215, 472, 459, 617, 649, 935, 956, 914, 932,
       645, 952, 921, 490, 527, 972, 278, 307, 840, 958, 246, 449, 251,
       957, 103, 627, 920, 824, 356, 825, 173, 323, 372, 960, 710, 464,
       244, 782, 763, 635, 436, 774, 171, 469, 178, 458, 624, 211, 771,
       270, 308, 231, 952, 514, 699, 702, 433, 900, 373, 318, 265, 503,
       320, 230, 324, 922, 967, 620, 743, 527, 117, 566, 804, 123, 946,
       587, 227, 853, 757, 944, 328, 855, 930, 325, 729, 426, 514, 296,
       879, 575, 936, 705, 209, 191, 743, 510, 513, 628, 559, 658, 528,
       395, 525, 922, 136, 496, 225, 895, 975, 263, 908, 420, 711, 800,
       976, 786, 235, 930, 859, 618, 226, 695, 460, 218, 483, 490, 803,
       621, 453, 193, 607, 677, 637, 728, 724, 534, 748, 291, 19

In [90]:
arr[0,np.argmin(arr)]

103

In [92]:
arr

array([[448, 563, 418, 240, 507, 362, 345, 236, 719, 291, 298, 639, 458,
        387, 262, 613, 267, 882, 181, 425, 790, 635, 889, 818, 872, 967,
        277, 470, 336, 920, 917, 295, 557, 830, 506, 385, 353, 975, 592,
        997, 137, 340, 222, 215, 472, 459, 617, 649, 935, 956, 914, 932,
        645, 952, 921, 490, 527, 972, 278, 307, 840, 958, 246, 449, 251,
        957, 103, 627, 920, 824, 356, 825, 173, 323, 372, 960, 710, 464,
        244, 782, 763, 635, 436, 774, 171, 469, 178, 458, 624, 211, 771,
        270, 308, 231, 952, 514, 699, 702, 433, 900, 373, 318, 998, 265,
        503, 320, 230, 324, 922, 967, 620, 743, 527, 117, 566, 804, 123,
        946, 587, 227, 853, 757, 944, 328, 855, 930, 325, 729, 426, 514,
        296, 879, 575, 936, 705, 209, 191, 743, 510, 513, 628, 559, 658,
        528, 395, 525, 922, 136, 496, 225, 895, 975, 263, 908, 420, 711,
        800, 976, 786, 235, 930, 859, 618, 226, 695, 460, 218, 483, 490,
        803, 621, 453, 193, 607, 677, 637, 728, 724

In [93]:
np.delete(arr,np.argmin(arr))

array([448, 563, 418, 240, 507, 362, 345, 236, 719, 291, 298, 639, 458,
       387, 262, 613, 267, 882, 181, 425, 790, 635, 889, 818, 872, 967,
       277, 470, 336, 920, 917, 295, 557, 830, 506, 385, 353, 975, 592,
       997, 137, 340, 222, 215, 472, 459, 617, 649, 935, 956, 914, 932,
       645, 952, 921, 490, 527, 972, 278, 307, 840, 958, 246, 449, 251,
       957, 627, 920, 824, 356, 825, 173, 323, 372, 960, 710, 464, 244,
       782, 763, 635, 436, 774, 171, 469, 178, 458, 624, 211, 771, 270,
       308, 231, 952, 514, 699, 702, 433, 900, 373, 318, 998, 265, 503,
       320, 230, 324, 922, 967, 620, 743, 527, 117, 566, 804, 123, 946,
       587, 227, 853, 757, 944, 328, 855, 930, 325, 729, 426, 514, 296,
       879, 575, 936, 705, 209, 191, 743, 510, 513, 628, 559, 658, 528,
       395, 525, 922, 136, 496, 225, 895, 975, 263, 908, 420, 711, 800,
       976, 786, 235, 930, 859, 618, 226, 695, 460, 218, 483, 490, 803,
       621, 453, 193, 607, 677, 637, 728, 724, 534, 748, 291, 19

### `Q-8:` You are given an arrays. You have to limit this array's elements between 100 to 200. $arr ∈ [100, 700]$. So replace those values accordingly with the minimum and maximum value. Then sort the array and perform the cumulative sum of that array.

In [102]:
# code here
arr=np.random.randint(100,700,10)
print(arr)
arr=arr.clip(100,200)
print(arr)
arr=np.sort(arr)
print(arr)
np.cumsum(arr)

[340 129 463 443 524 197 523 662 571 637]
[200 129 200 200 200 197 200 200 200 200]
[129 197 200 200 200 200 200 200 200 200]


array([ 129,  326,  526,  726,  926, 1126, 1326, 1526, 1726, 1926],
      dtype=int32)

### `Q-9:` You are given a array ($arr ∈ [0, 1]$). First you have round off the elements upto 3 decimal places and compare that
- 0th percentile == minimum value of the array
- 100th percentile == maximum value of the array
- also find the difference betwen 51th percenile and 50th percentile values

In [42]:
# code here

arr=np.random.random(100)
print(arr)
arr=np.around(arr,decimals=3)
print(arr)
print(np.percentile(arr,100))
print(np.percentile(arr,0))


[0.98075268 0.39300353 0.17577617 0.60864612 0.11424243 0.01134365
 0.41929829 0.07902473 0.00673664 0.34397174 0.30910187 0.82953737
 0.3337228  0.14766079 0.69611825 0.73636098 0.39532036 0.27632201
 0.91950315 0.9349746  0.22166568 0.42974373 0.68080542 0.48072058
 0.74792497 0.89255942 0.54768646 0.56579862 0.92903106 0.19499544
 0.64201342 0.40503014 0.79920004 0.93289982 0.15379172 0.87597506
 0.47012835 0.7910476  0.54946733 0.0258041  0.08468146 0.4544235
 0.07118497 0.79658163 0.40068467 0.8380174  0.45432315 0.43571153
 0.40025534 0.15953643 0.19344388 0.49061865 0.48101087 0.53831366
 0.78281695 0.67303325 0.425004   0.09682484 0.50122405 0.80982492
 0.23410432 0.66897394 0.19880221 0.2428051  0.65272368 0.83753612
 0.26467711 0.18611446 0.50983086 0.81815127 0.49039409 0.63487748
 0.33040376 0.51094455 0.86051298 0.27238922 0.07730484 0.34270206
 0.19014881 0.05716238 0.84324686 0.22366672 0.13183421 0.33492168
 0.85075388 0.25727505 0.91568392 0.47927837 0.36811304 0.71687

In [43]:
print(np.percentile(arr,51)-np.percentile(arr,50))

0.005479999999999985
